name: Fly deploy
on: [push]
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  VITE_PUBLIC_APP_NAME: lnkd
  VITE_PUBLIC_APP_URL: ${{ secrets.VITE_PUBLIC_APP_URL }}
  VITE_PUBLIC_APP_LINK_URL: ${{ secrets.VITE_PUBLIC_APP_LINK_URL }}
  VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
  VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: superfly/flyctl-actions@1.1
        with:
          args: "deploy"